### ISSUE TITLE
Allow ability to specify script type in Asset::add()

### ISSUE THREAD

**Issue by thachp** [RoumenDamianoff/laravel-assets#17]
IE,

     {{ Asset::add('/js/sample.js','footer','text/jsx'); }}

Would output this HTML markup in the footer.

    <script type="text/jsx" src="/js/sample.js"></script>

Source:
http://facebook.github.io/react/docs/getting-started.html#offline-transform

**Comment by RoumenDamianoff** [comment]
Now you can do this:

```php
Asset::add('js/some.js', ['name'=>'footer', 'type'=>'text/jsx']);
```
