### ISSUE TITLE
Passing attributes to js ?

### ISSUE THREAD

**Issue by rombat** [RoumenDamianoff/laravel-assets#20]
Hi,
Is there a way to pass attributes like 'defer' or 'async' to js?
That would be a great option.

**Comment by RoumenDamianoff** [comment]
Hi, right now you cant do this, but this is in my to do list for the next update.

**Comment by RoumenDamianoff** [comment]
Now you can add js assets with custom attributes (name is required, type, async and defer are optional):

```php
Asset::add('js/some.js', ['name'=>'footer', 'type'=>'text/jsx', 'async'=>'true', 'defer'=>'false']);
```
