### ISSUE TITLE
Add asset only once

### ISSUE THREAD

**Issue by elite123** [RoumenDamianoff/laravel-assets#22]
I'm getting console errors when a script gets added multiple times and therefore causes a conflict, would it be possible to use the script path as a key in the scripts array, therefore preventing multiple additions?

/**
     * Process add method
     *
     * @param string $a
     * @param string $name
     *
     * @return void
    */
    protected static function processAdd($a, $name, $onUnknownExtension = false)
    {
        switch (static::getAddTo($a, $onUnknownExtension))
        {
        	case static::ADD_TO_CSS:

        		static::$css[$a] = $a;
        		break;

        	case static::ADD_TO_LESS:

        		static::$less[$a] = $a;
        		break;

        	case static::ADD_TO_JS:

        		static::$js[$name][$a] = $a;
        		break;
        }
    }

**Comment by hackel** [comment]
Wait, this package doesn't already do this?  That was my only reason for wanting to install it!  Otherwise, the functionality is already built-in to Laravel/Blade.

**Comment by RoumenDamianoff** [comment]
Now scripts are added only once and all duplicates are ignored.
