### ISSUE TITLE
Adding assets not working

### ISSUE THREAD

**Issue by maxi032** [RoumenDamianoff/laravel-assets#23]
I want to add a css to my blade template file and I do 

   {!! Asset::css('foo/bar.css') !!}

Nothing shows

**Comment by RoumenDamianoff** [comment]
This is not how its done. See the [wiki](https://github.com/RoumenDamianoff/laravel-assets/wiki), you need to add the script first with ```Asset::add('styles/default.css');``` and then to use ```Asset::css();``` in the layout/view.

**Comment by mirzap** [comment]
Where do you put  ```Asset::add('styles/default.css');````?

What is the location of the assets? Laravel default? Is it possible to set different dir for the assets?
